[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
auto_detect_solc = true
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "@uniswap/permit2/=lib/permit2/",
  "@uniswap/universal-router/=lib/universal-router/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/v3-periphery/=lib/v3-periphery/",
  "@uniswap/v2-core/=lib/v2-core/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
  "v4-periphery/contracts/=lib/v4-periphery/src/"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

